---
collections:
  - name: ansible.posix
    version: 1.5.4

  - name: ansible.scm
    version: 3.0.0

  - name: ansible.utils
    version: 5.0.0

  - name: https://github.com/redhat-cop/network.backup
    type: git

  - name: manala.roles
  - name: community.general
roles:
  - name: tomereli.oh_my_zsh_p10k
  - name: monolithprojects.homebrew
