---
all:
  hosts:
    proxmox:
      ansible_host: 192.168.1.202
      ansible_user: root
    pelican:
      ansible_host: 192.168.1.157
      ansible_user: pelican
    arr-suite:
      ansible_host: 192.168.1.213
      ansible_user: root
